  spring:
    application:
       name: activity-service
    cloud:
      config:
        enabled: false
    config:
      import: "optional:classpath:/"
    data:
      mongodb:
        uri: mongodb+srv://ravirkumar2422:lba8qWzdGWadOrU2@cluster0.pdnfl7u.mongodb.net/fitnessactivity
        database: fitnessactivity


  server:
    port: 8082

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/



